(function initEmailShareHelper(global) {
  if (global.EmailShareHelper) {
    return;
  }

  function clean(value) {
    if (value === null || value === undefined) {
      return '';
    }
    if (typeof value === 'number') {
      return Number.isFinite(value) ? `${value}` : '';
    }
    return String(value).trim();
  }

  function toReadableUrl(url) {
    const value = clean(url);
    if (!value) {
      return '';
    }
    try {
      return decodeURI(value);
    } catch (error) {
      return value;
    }
  }

  function stripProtocol(url) {
    const value = clean(url);
    if (!value) {
      return '';
    }
    return value.replace(/^(https?:\/\/)/i, '');
  }

  function sanitizeCategories(categories) {
    if (!Array.isArray(categories) || !categories.length) {
      return [];
    }
    return categories
      .map(entry => clean(entry))
      .filter(Boolean);
  }

  function buildYearSummary(options = {}) {
    if (options.yearSummary) {
      return clean(options.yearSummary);
    }

    const singleYear = clean(options.singleYear);
    const startYear = clean(options.startYear);
    const endYear = clean(options.endYear);

    if (startYear && endYear) {
      return startYear === endYear ? startYear : `${startYear}-${endYear}`;
    }

    return singleYear || startYear || endYear || '';
  }

  function buildYearNarrative(options = {}) {
    if (options.yearNarrative) {
      return options.yearNarrative.trim();
    }

    const startYear = clean(options.startYear);
    const endYear = clean(options.endYear);
    const yearSummary = buildYearSummary(options);

    if (startYear && endYear) {
      if (startYear === endYear) {
        return `for ${startYear}`;
      }
      return `from ${startYear} to ${endYear}`;
    }

    if (yearSummary) {
      return `for ${yearSummary}`;
    }

    return '';
  }

  function composeEmail(options = {}) {
    const pollutantName = clean(options.pollutantName) || 'Selected pollutant';
    const yearSummary = buildYearSummary(options);
    const yearNarrative = buildYearNarrative({ ...options, yearSummary });
    const shareUrl = clean(options.shareUrl);
    const readableShareUrl = stripProtocol(toReadableUrl(shareUrl));
    const categories = sanitizeCategories(options.categories || options.groups);

    const subjectParts = [`UK Air Pollution/Emissions Data: ${pollutantName}`];
    if (yearSummary) {
      subjectParts.push(yearSummary);
    }
    const subject = subjectParts.join(' ').replace(/\s+/g, ' ').trim();

    const bodyLines = [];
    const intro = `I'm sharing UK air pollution/emissions data for ${pollutantName}${yearNarrative ? ` ${yearNarrative}` : ''}.`;
    bodyLines.push(intro);
    bodyLines.push('');
    bodyLines.push('Categories included:');

    if (categories.length) {
      categories.forEach((category, index) => {
        bodyLines.push(`${index + 1}. ${category}`);
      });
    } else {
      bodyLines.push('None specified');
    }

    bodyLines.push('');
    if (readableShareUrl) {
      bodyLines.push(`Interactive chart: ${readableShareUrl}`);
      bodyLines.push('');
    }
    bodyLines.push('Generated by the Chronic Illness Channel UK Air Pollution/Emissions Data Explorer');
    bodyLines.push('chronicillnesschannel.co.uk/data-explorer');

    return {
      subject,
      body: bodyLines.join('\n'),
      yearSummary,
      yearNarrative
    };
  }

  function openEmailClient(payload) {
    if (!payload || !payload.subject || !payload.body) {
      return false;
    }
    const subject = encodeURIComponent(payload.subject);
    const body = encodeURIComponent(payload.body);
    global.location.href = `mailto:?subject=${subject}&body=${body}`;
    return true;
  }

  function composeAndOpen(options = {}) {
    const payload = composeEmail(options);
    openEmailClient(payload);
    return payload;
  }

  global.EmailShareHelper = {
    composeEmail,
    openEmailClient,
    composeAndOpen,
    toReadableUrl,
    stripProtocol,
    formatYearSummary: buildYearSummary,
    formatYearNarrative: buildYearNarrative
  };
})(window);
