// Auto-generated by scripts/generate-supabase-env.js on 2025-12-08T13:24:42.424Z
// Source env file: /Users/mikehinford/Dropbox/Projects/CIC Website/CIC Data Explorer/CIC-test-uk-air-pollution-emissions-data-explorer/.env

window.__NAEI_SUPABASE_CONFIG = Object.freeze({
  url: "https://buqarqyqlugwaabuuyfy.supabase.co",
  key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1cWFycXlxbHVnd2FhYnV1eWZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyOTczNDEsImV4cCI6MjA3Njg3MzM0MX0._zommN8QkzS0hY__N7KfuIaalKWG-PrSPq1BWg_BBjg",
  storageKeyBase: "sb-buqarqyqlugwaabuuyfy-auth-token"
});
