-- Supabase schema reference for CIC Data Explorer
-- Last updated: 2025-12-11
-- This file documents the tables and views the front-end relies on, so we can keep
-- the Supabase project in sync across environments.

/* -------------------------------------------------------------------------- */
/*  Core read-only NAEI dataset tables (provisioned upstream).                */
/* -------------------------------------------------------------------------- */
-- public.naei_global_t_category          -- Category metadata (source/activity lists)
-- public.naei_global_t_pollutant         -- Pollutant definitions + units
-- public.naei_2023ds_t_category_data     -- Yearly category values for pollutants
-- public.naei_global_t_sourcename            -- Source lookup table (id + source_name)
-- (The core datasets are managed outside this repo; definitions documented in the
-- Supabase console. They are listed here for completeness.)

/* -------------------------------------------------------------------------- */
/*  Application-owned tables                                                  */
/* -------------------------------------------------------------------------- */

-- Table: public.color_source_rules
-- Purpose: map specific source_ids to colour tokens, optionally marking them as
--          exclusions. Lower priority numbers win when multiple rules match.
CREATE TABLE IF NOT EXISTS public.color_source_rules (
    rule_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id       INTEGER NOT NULL,
    color_token     TEXT    NOT NULL CHECK (color_token <> ''),
    rule_kind       TEXT    NOT NULL DEFAULT 'assign'
                              CHECK (rule_kind IN ('assign', 'exclude')),
    priority        INTEGER NOT NULL DEFAULT 100 CHECK (priority > 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID DEFAULT auth.uid(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID DEFAULT auth.uid()
);

COMMENT ON TABLE public.color_source_rules IS 'Source-driven colour mapping rules for the charts';
COMMENT ON COLUMN public.color_source_rules.color_token IS 'Matches palette tokens (orange, red, blue, etc.)';
COMMENT ON COLUMN public.color_source_rules.rule_kind IS 'assign = prefer this colour, exclude = block this colour when source present';

CREATE INDEX IF NOT EXISTS idx_color_source_rules_source_id
    ON public.color_source_rules (source_id);
CREATE INDEX IF NOT EXISTS idx_color_source_rules_priority
    ON public.color_source_rules (priority);
CREATE UNIQUE INDEX IF NOT EXISTS uq_color_source_rules_source_color_kind
    ON public.color_source_rules (source_id, color_token, rule_kind);

ALTER TABLE public.color_source_rules ENABLE ROW LEVEL SECURITY;

-- Allow anyone (anon + authenticated) to read rules
DROP POLICY IF EXISTS "color_rules_read" ON public.color_source_rules;
CREATE POLICY "color_rules_read"
ON public.color_source_rules
FOR SELECT
USING (TRUE);

-- Only the service role (used by admin scripts) can insert/update/delete
DROP POLICY IF EXISTS "color_rules_manage_service" ON public.color_source_rules;
CREATE POLICY "color_rules_manage_service"
ON public.color_source_rules
AS PERMISSIVE
FOR ALL
TO service_role
USING (TRUE)
WITH CHECK (TRUE);

GRANT SELECT ON public.color_source_rules TO anon, authenticated;
GRANT ALL ON public.color_source_rules TO service_role;

/* -------------------------------------------------------------------------- */
/*  View exposing friendly source names                                       */
/* -------------------------------------------------------------------------- */
-- Join the rule table with the master source lookup so editors can see names.
-- Adjust the join target if your source lookup table uses a different name.
CREATE OR REPLACE VIEW public.color_source_rules_with_sources
WITH (security_invoker = true) AS
SELECT
    r.rule_id,
    r.source_id,
    s.source_name,
    r.color_token,
    r.rule_kind,
    r.priority,
    r.created_at,
    r.created_by,
    r.updated_at,
    r.updated_by
FROM public.color_source_rules r
LEFT JOIN public.naei_global_t_sourcename s
  ON s.id = r.source_id;

GRANT SELECT ON public.color_source_rules_with_sources TO anon, authenticated;
GRANT ALL ON public.color_source_rules_with_sources TO service_role;

/* -------------------------------------------------------------------------- */
/*  Seed data for colour mapping rules                                        */
/* -------------------------------------------------------------------------- */
-- Colour mapping v2.0 (source: system_docs/Colour mapping v2dot0.csv)
INSERT INTO public.color_source_rules (source_id, color_token, rule_kind, priority)
VALUES
    -- Orange assignments
    (204, 'orange', 'assign', 1),

    -- Red assignments
    (208, 'red', 'assign', 1),
    (202, 'red', 'assign', 2),
    (205, 'red', 'assign', 2),
    (203, 'red', 'assign', 2),

    -- Blue assignments
    (219, 'blue', 'assign', 10),
    (220, 'blue', 'assign', 10),

    -- Green assignments
    (685, 'green', 'assign', 10),

    -- Cyan assignments (road transport family)
    (738, 'cyan', 'assign', 10),
    (739, 'cyan', 'assign', 10),
    (740, 'cyan', 'assign', 10),
    (741, 'cyan', 'assign', 10),
    (742, 'cyan', 'assign', 10),
    (743, 'cyan', 'assign', 10),
    (744, 'cyan', 'assign', 10),
    (745, 'cyan', 'assign', 10),
    (746, 'cyan', 'assign', 10),
    (747, 'cyan', 'assign', 10),
    (748, 'cyan', 'assign', 10),
    (749, 'cyan', 'assign', 10),
    (750, 'cyan', 'assign', 10),
    (751, 'cyan', 'assign', 10),
    (752, 'cyan', 'assign', 10),
    (753, 'cyan', 'assign', 10),
    (754, 'cyan', 'assign', 10),
    (755, 'cyan', 'assign', 10),
    (756, 'cyan', 'assign', 10),
    (757, 'cyan', 'assign', 10),
    (758, 'cyan', 'assign', 10),
    (759, 'cyan', 'assign', 10),
    (760, 'cyan', 'assign', 10),
    (761, 'cyan', 'assign', 10),
    (762, 'cyan', 'assign', 10),
    (763, 'cyan', 'assign', 10),
    (764, 'cyan', 'assign', 10),
    (765, 'cyan', 'assign', 10),
    (766, 'cyan', 'assign', 10),
    (767, 'cyan', 'assign', 10),
    (768, 'cyan', 'assign', 10),
    (769, 'cyan', 'assign', 10),
    (770, 'cyan', 'assign', 10),
    (771, 'cyan', 'assign', 10),
    (772, 'cyan', 'assign', 10),
    (773, 'cyan', 'assign', 10),
    (774, 'cyan', 'assign', 10),
    (775, 'cyan', 'assign', 10),
    (776, 'cyan', 'assign', 10),

    -- Green exclusions (stove/fireplace safeguard)
    (204, 'green', 'exclude', 1),
    (202, 'green', 'exclude', 1),
    (205, 'green', 'exclude', 1),
    (203, 'green', 'exclude', 1),
    (208, 'green', 'exclude', 1)
ON CONFLICT (source_id, color_token, rule_kind) DO UPDATE
SET priority = EXCLUDED.priority,
    updated_at = NOW();
